version: "3.9"

services:
  db:
    restart: unless-stopped
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django:
    container_name: django
    restart: unless-stopped
    build:
      context: ./
      dockerfile: docker/django.Dockerfile
    command: python manage.py runserver 0.0.0.0:8008
    volumes:
      - ./backend:/backend
    ports:
      - "8008:8008"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  nodejs:
    container_name: nodejs
    restart: unless-stopped
    build:
      context: ./
      dockerfile: docker/nodejs.Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    #    command: npm run watch
    volumes:
      - ./frontend:/frontend
      - '/frontend/node_modules'
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - django